import { jsPDF } from "jspdf";

/**
 * Generates a professional PDF report for VaultVision.
 */
export const generateVaultVisionPDF = async (assetName: string, analysisText: string, confidence: number, riskLevel: string) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // 1. Add Header Background
  doc.setFillColor(10, 5, 29); // VaultVision Dark theme color
  doc.rect(0, 0, pageWidth, 40, 'F');

  // 2. Add Logo (Assuming /logo.png is available)
  try {
    // We try to fetch the logo as a base64 string for jsPDF
    const logoUrl = "/logo.png";
    const response = await fetch(logoUrl);
    const blob = await response.blob();
    const reader = new FileReader();
    
    const logoData: string = await new Promise((resolve) => {
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });

    doc.addImage(logoData, 'PNG', 10, 10, 20, 20);
  } catch (e) {
    console.error("Could not load logo for PDF:", e);
    // Fallback: Just draw a blue circle if logo fails
    doc.setFillColor(0, 174, 239);
    doc.circle(20, 20, 10, 'F');
  }

  // 3. Add Title (Centered)
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("VAULTVISION", pageWidth / 2, 22, { align: "center" });

  // 4. Report Metadata Section
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.text("FORENSIC ANALYSIS REPORT", 10, 55);
  
  doc.setDrawColor(200, 200, 200);
  doc.line(10, 60, pageWidth - 10, 60);

  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text(`Asset Name: ${assetName}`, 10, 70);
  doc.text(`Match Confidence: ${(confidence * 100).toFixed(1)}%`, 10, 78);
  doc.text(`Risk Classification: ${riskLevel}`, 10, 86);
  doc.text(`Date: ${new Date().toLocaleString()}`, 10, 94);

  // 5. Analysis Content
  doc.setFontSize(12);
  doc.setFont("helvetica", "bold");
  doc.text("EVIDENCE ENGINE ANALYSIS (Gemini 1.5):", 10, 110);
  
  doc.setFont("helvetica", "normal");
  doc.setFontSize(11);
  
  // Use splitTextToSize to handle long text and line breaks
  const splitText = doc.splitTextToSize(analysisText, pageWidth - 20);
  doc.text(splitText, 10, 120);

  // 6. Footer
  doc.setFontSize(8);
  doc.setTextColor(150, 150, 150);
  const footerText = "Generated by VaultVision AI - Securing the Future of Digital Sports.";
  doc.text(footerText, pageWidth / 2, doc.internal.pageSize.getHeight() - 10, { align: "center" });

  // 7. Save the PDF
  doc.save(`VaultVision_Report_${assetName.replace(/\s+/g, '_')}_${Date.now()}.pdf`);
};
